"""Add relationship in Document

Revision ID: c236b1e1c852
Revises: 26cb3319bd72
Create Date: 2023-08-24 07:59:27.438075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c236b1e1c852'
down_revision = '26cb3319bd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
